### ISSUE TITLE
Can't get the host working with docker image :(

### ISSUE THREAD

**Issue by nicedevil007** [wHyEt/Awtrix2-Docker#5]
Heya, just tryed to install the docker container on my Pi 4 with 32bit DietPi on it.

Here is the docker compose file I've been using to get it done:

```
version: '3.7'

volumes:
  data:
  
networks:
  backend:

services:
  app:
    image: whyet/awtrix2
    container_name: AwTriX2
    restart: unless-stopped
    networks:
      backend:
    ports:
      - 7000:7000/tcp
      - 7001:7001/tcp
      - 5568:5568/udp
    environment:
      #JAVA_TOOL_OPTIONS: "-Duser.language=de -Duser.country=DE"
      TZ: Europe/Berlin
    volumes:
      - data:/data
```

The log of the container always tells me this:

`Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: task sh004ryxyj859rwoajcosg6no has not been scheduled`
